version: '1.0'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_DATABASE: case_studies
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: cases123
      DATABASE_NAME: case_studies

volumes:
  db_data:
